sudo: required
language : java
jdk: oraclejdk8

env:
  global:
  - DOCKER_USER="ZDJuhG+Z8W9D0WGz9BCkn6cyJwQaFKSm9dFMNZ7RSHTHHpwn0E74NTGrXA9zKOWLHdCqnapXgI+wr6aMH7OmQKo2w9Nm5Yf5QnP5RdpxztUDTcqGQmn7ccvZgvybIvcK+Gxq/50/Z8EJc4n+syPW79pMZzvoziGp52At33pTuYHZA1MIcxZmeNd3DyTDsfiP1qmRlChfIZ2yaD2zt17lEFDnYZrtv1Qw66F78mUR2nFUIDSaleevAIqzDxbaVgOV/0ATvgmcyZC4EdcIkouoiAV9RctuHiH8SABUQdprl2NB3VFvKLBSqHJMb7oQ3kcTD7jmaOJq+Ns3jqu+f1n8QRH0DVfIV6cO1PCvbryHewjJmYQWpQgFOofdJihLYzfPd9ANBak8HWXtzxHuLLkHU8FHfaFMiUCVwRDMd15u9l5qqEMJsxpyfkCczvxdlhft1Dfgq/PjAECKVpHe8XfzPRcpXXBLcOhhL3gxtIWvuUlyZumHzUdbQ+mTOyJC6ny7whLueuUIm6pki2hLywXHdcYTnVfWEXIcO6VbJTxBbG1lsKVQxwdEsXiqU2DokwBPgZtdPnK4xo3JjVCiDfCfx+mt8pISiAsbKU25uVoj9XIHRiMOLdgYwCNe6c1eV6lEiwHIu6Zwcz7thFFqi+12x1BNv3USPEj1tIT9h94r4J8="
  - DOCKER_PASS="QyzWABgCrEPCqiK8E+/RczZfdLqysjank3eHCZXUEIKUMDNFxA63mWzNltHsIJXWhI/8ojK+TEeScFW/SS6ADzWOuxx5DAvM1+P1eJPtZHsF0T51bT7/fEju/kBcxJz3uBuYwiw90udXJBcg+qK+iohTCUhrFwbSSAmwqYlX4Jx7bZyXD4p1Lgezmw/+IVD4hBPsvDlMadH4M/4mkFFoReQ6ir5co6N6INY6QrobOciGnTqfso2pwKfkQ0NFq3080iYKaD8bjE2xdDWiU0I/Om9g5DCb9aIzMJlmfPZmy2Bu/icfDtDdLSv4bEjg0q7pRCjf4VEoZ2RpNZJn8I4qlED3lLHGteiBFYfFf6AG4lHYdVf7OjCgDF/ix0fpJ8Wlx59lW1t01D04dWthrg4yjDPW0UCkrtmXKlc2PlNYQDllg0yWxFOQP2i5yDMdS59SdOnnfmlh42EKNnSbkwpoYb+UCuBdjbRHBChnoEzsX62urNWWUbsqX7fO6vckXpGg/s3698F5yH06lYC3gsJBvYaz0zH2T2IN5joYluqXb4w4KO+UYJbuLIeNECnr+hHAJ+vllbq7BMhstdeJSPOheaYcHWsro5Ydq7Oi+pZbckIh5+iy7XCNG8XJ1kO6xQboyaHhoy3WDLf5R5QpwKjIOtO8rPgDMvS+vjeqvxqb+BQ="
  - HEROKU_API_KEY="LjL4w089ZDcunOZ/aCBMHOZ5oNGBlKPbXer78DbxwkYkUeTwaT/7j760cFwD6kpX6rSoENPUDy9atoIHbs+RIZSNlu2zE2SGH5Df3r/zOrRrZ1GVRtmjNw1WKcKnceurN0c5dih/6pjtvXoY75v+fGcvic/WgydvM0xfDRNss1zbuzu3NLwOtyzHgfXZfiB7FR93eMec6UYJg85Z4IrcdsY5ElYjprYESZBpsVBaDcGev224vzzuzdEeIU+Z2du8QutUDcz2RMdDywAnyobyyDDVdWLH7DXZc7rBD7JTWlLi95FDHc8kQ9hYJHP4PlJqrCIbYgoe6GaDbmFeam86AXKmK2MZCqQAZ4FfamyqTm6t5EY7ZtvhqBjXKurX18p7USbOBuwHvUHX/e16IsqlRW/4n3e/lZNezQBdMITQMAf8MQyK6UJ+c2SKowCbV9JHlxOtn/bJPQhRz7YND3GeAjbaFd42DyLxKbT3e6pI2mnWrP5VZCA6ttcO2TwMOhQuhRRwxMgViQjBGNcygRtLLWSBtFUUzdsDAsOEQ2cdb6Xo4ECDlwbVM6ScQ1tBEPD/PfXmzshuG26W6kSUxinUbvxmOZ+K675OdAnvZOs27gqPzE0+eVft6nAhzac/BHQJBVqCOzBd9MdKQz7PTiHErdJ3Fw2iGfMRa8WY5xWXwGc="
  - COMMIT=${TRAVIS_COMMIT::7}

script:
- ./gradlew clean test
- ./gradlew jacocoFullReport

services:
  - docker

after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH; fi`
  - export IMAGE_NAME=ianarb/restaurant-looker-api
  - docker build -t $IMAGE_NAME:$COMMIT .
  - docker tag $IMAGE_NAME:$COMMIT $IMAGE_NAME:$TAG
  - docker push $IMAGE_NAME

deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: blooming-basin-97212

