sudo: required
language: java
jdk: oraclejdk8
env:
  global:
  - secure: QVohElGXZnx45E0K2np8TRnsc8GlBYzt6BByKVAk/g3o98oKTLqyHWwcVuo6O6+C7zRDNGXVNxY+Kaww8J4BUnzvaHKLCMUdFKM2nPYwx3YGQTQqezhsG94ConC9COqTz+wTdL6rBpgyBgroK29m9NGk/fsiIr7053fAhN1CP0RUkV6YXbz20k8SDhd4q1DknU7Atdgo9mEgEO7PhkiAX8Pv+n4ISwv/glPS+xSpec0jykLnWuUWSXIpaswuUNUr7q7aCYZwQq9B/VE01a9rWeH/6e305Eu7ODKXENKxVPSFau0JZaIY1XTAtM09ro9rOOrEaV8lXjUsfZsgdB67NS3uerDvBhuBlPJkHAXRBB4OsZaZZCRNcv9E0VyLdLcRibPdwfJaPJN1BdNrx898oL04eNXOEf6ANMPBi6Xl1eYBxKGvtOI0SpEF7JkVnJEdQQEE0RN+Wbv2K6pWH0OCV1aK0ItkgVqwJLhRvuf/KNLQ9qfrbBotiv2tfwDa8k0hY6pgYoNZ2/zUDrvjeGLYVH7b/uQM0nDNzGj3aiaBnv9wZxwQqT2tqoDFswB2VpIdkvhqrdd9chA3UqxHpFI6/LFoICD3+qh1OBX76DliR2S6s6ZbzJZKLb1UqNNEKKQ3mRT1mDARLWTR/db7XmYVhcLlbyMzGjbMSsGHYqPci7M=
  - secure: HxUNtZJkU/2BoZdIKM62I2CLGrYpsQDO7/6XOaD+Y5YIoI4+xSSVd+KCvMbCnQagakVDqsJ9AMOliXxgjOmVQ9KI6xQ4/jTxpTmpv4keMiIe0jU6w1M91NzHzrHuHawiX6XfI94CB5AKncOaGEBAsb2DzbVyIQ1ZDQN8OPoXf+734U1ZhrN/D3gCGtXElZYI1R5qf7L/MbtZgqvFKE6vQLG+dvGHOGPnuhVowwEZFGr/obQfbWTT5Qo2gYsSrYehaBbv+zYnaU7OH1VBK2ww2TiY7a88Xcjpuz+o9fCkhXsqpv3YdpgYG3bWZxli6VPEHxAuty5h7pg81c7TAAUZ1nQuPjQ5atey+M2ztVTs7dzZQQ0jMucnOZ0RNydAoh7NHjsrgntmmSe0QdSJstMSMOs9IOg58bCuQdlEUpV+d5XLtQiuNZAbpeC1R0xXkQnF0K96b1KWJwYIuZN3o/XWsDEN7XN5au9UqJlOSo4oX8UL5W5tKMfmIxQaexgr6G0wz8FWdlNOH5/T0iOOWDVmudlkh0LfnpLvC/AJmGhecb6Ur0q/3z44fezpS9lc9XqzTonMrwfDjrpYyKrTWo1Tt/euDEi6rapsdF4MvagH6R9w1x+VqKerI+blgHpQwTkH11uf4n+eHNbgyueOwAqzsPp0hl3LPGQz9yu/AUfXSMQ=
  - secure: ka0Mkj8/FXn/GQXbBpD73LLD0BdUj9NueDZuDlbP7eM4Yrh3ajRWqV0I/AMKMJYiVu81R6nkUxXeDKFYsFS8SA42/yotw8Pa+9yF2u/SrKwWbEZZb25bpUpAng2CDaG5A1HhkfxPlpjqOkPQm9oBWvdeC7EtHvoWtNF7uRe/7YzdIMCghyVq46uNfqb/ECtLGg+jJReAoOh1vu+EIb/lAWCOlF+07EHEdi1ubKz30l2vHA8nIaPSAA1oKb6inxz4vqD2fyB4144IKdZHFmc31Ljm2gAxFo7ivySfvC/nim0RARQY3uQz4zGuLqv++GKGzeymgH+Exq1vohmDFlMo95/lfi8C+dzz0Kjp8MagUetncTurs8RLPBTCD1iIvvndGz8T5PPgcChXpzFVTNuF1yJI0RluoG+hE23vz7Ey99iT/WuVaYH0DYibu/ZR02B+EqKKPvT4xCJxCitGh+nPLeMTY3nOhgeerTVjUyIJtSrHQxpMEY31BG6e1X1S2sHDyrOqU6qN3QAh9H2YKFW3clMkrBkUffx4s3AbgauiJBFb4LBIhTP4N2Y4w9T1mDiYKp7a6bOvvGLjsnMWu5cfxxlAvvxlqlRz20Qsbvd52Uvu1SEYuZTlBvMp7VOvHqBSMwJiqYUbz/3lvX1+x8QA3MewZsnus3hwUozQ7mLPJfk=
  - secure: nAf9AjuL0gia8NjDPY4I82mEKsY5cQqHv77kI471lxmTSWTxu/BN53ar+Q/MKjks5AKfwFgeg/jlbOtyM5+4p0Mn2xsOs23QQ3wpbeBud6t3aquu9bfEW+tagZ9fjQba1IeBaTDyTL/jf7ch08nkRGL+iaFXKxCvcEclWMwW49HiZzmicdtbXJJ113lYgMxNO5nAIaDdPB3dE6ROjXyYJldpsMY2lFG+hVuxPjAn8+SBbsprDb8xr5pnI27Y/7hgd2KZroSzfzAIZY9WGFCEZQFzutrdTM9DgOmM4T4kdUt90STsJ+PZeq5JOmtfr0xS8u7Uymj2cZBVWGcdufMFk3Lo2Ca/+aWHul3ebSO0/Fn/HtzN2gafsf8HJNsLPWOQUuLFjk4LNUusfJe/h3Ppk4JXPArMZcutWUraZzmIq+YeVfDN5T/wtsZzcVDEiPqYMHxk0fOL+l1+SFdla3BCSz/n9NsgfSy7sV3ESojfBhs4unl1LULE3pckT2bJ5eIpD3j+pC81LAtwu8T4owAfsPh3ft/n0P7bBgQyEA7wn7h8poQVn7kN8qeph9wN28f8cRSqnNmYWOC8Rx1aE5nrxuSeHu4y3Wbf+6ocNyvXT3t2Qm0VAsSO6Jr8zyeQi3tYvgRWI/vPiyTWjx6NRdwdEVYVf1J6gJvdHr6xKLaIPv0=
  - COMMIT=${TRAVIS_COMMIT::7}
script:
- ./gradlew clean test
- ./gradlew jacocoFullReport
services:
- docker
after_success:
- docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH;
- export IMAGE_NAME=ianarb/restaurant-looker-api
- docker build -t $IMAGE_NAME:$COMMIT .
- docker tag $IMAGE_NAME:$COMMIT $IMAGE_NAME:$TAG
- docker push $IMAGE_NAME
deploy:
  - provider: s3
    access_key_id: AKIAYUK2ULG75OR6MAAP
    secret_access_key:
      secure: UAPjYTsiSFHffbNLLsjfut9HQKQtx9Mkfbfw7nfmOS6teSLWnGrr6G/H67e/XXHHXOUshK1hX4Hba40IsiyGJ4jF1rHFVFhlry61ewqzR+Ixs+O+jMfH4qhCaFE2HcqVRxrFDouQnxoQdEXCA3UpCo0RpHaZWIByf7gd3xmMbufaPiZxkAcGowkCQEfcK2FhnYTEIV5US+k9/QEkI5N5IBClzZ5W+U20yLxRdpHhrJ4s/VEmtRDUh5dwpd7q5D9CSJiBo4bxmZ1UsY7/BSYjqJjE+sNV83u9I72UpsJh0WVW3AJvui8VOqVw5qMHAvteVC/jH6bXFoFIkVwvaB2PNb04Wd+HuvR1oT51tfKFO3KGo5xb/DpXTjcAOBS/WqzzBWgIvHY7NuhtwOm6UHMxTm4SwMEPkWkgxZEPP4jQb+RjV4b16zPfSZog3rB7QF+Ma8UOPvjax403E2/SPuocYGsA41z2Kv9Ye1zCJlb7crTVe6HZnntr0okYo5jBmWTqymvjfOp5QX9tgZ3JcMlBBRlYlqI8uLUEpnXWuoYeFHAJmPHVVBKSUp7GPGKQ+3yEicDl7jAOlqCC5eFdsc+H9ahaxP8YlLR04jukUIK3LF8IWXInv9gvPwtx4c2XGiisPlBhawN++gWd4s14xh47JOerDJCTXwKIBXbaDri22jc=
    bucket: ian-arbuckle-restaurant-looker
    local-dir: build
    on:
      repo: IanArb/restaurant-buddy-api
      branch: master
  - provider: codedeploy
    access_key_id: AKIAYUK2ULG75OR6MAAP
    secret_access_key:
      secure: eG492X\/cPq\/mIi\/LYZpXzbNbqvmoaB6gZ8YgXo2O5OFdVcZQK2hEGOIwASkATM14VswfmlRpvslHF6ByRrCc4LubqkwFN1eIJWwPuFb7FCpgzlIW6hL151fSYAubZJEH4urHNbTTjCdGBA7ACip0pARRYqeNHg1oqQxbZS51OW0QdqgHXd7QrcvfLwXxGQJZUkgPOPICi\+3Rt84g4sGdzcOPKme5NQTQqH6hCmr8xdAJC\/Z59VgNm3fRxW2avDQMvUpHMpB1l\+\/Vre4rLjL8QvqjhR7R0noDJYdHYMNWH\+mWUT\/vpBOFrf3GES3As7yKicA3000FjKgKsWutv95M\/AYRNf9dMSoKDYXhQF0hobn8aZ\+\+1gKA2cKu8hbrk2XOLZnwlrm4w89bt6AgJSq18II\/8yzWwRhYBT\+tfYJV4xv4s4WJ9F0tc5L\+S\apyiO0d\/yOQwQ3b\/HXJf66qghWjvG1pHxyivK4scuz27sBwAJRl\/+8rFsyfDSUUQOkuSf\+iv57IRB4q0vJkt78XiCgTD63Bb6sRMTYIADqywK79jk3XtBLOYKWF8amsO7sCyXIqtZpkHT0Vzrdl4akfIEBTzB4\+ntUy81IRK76JC6HrSH1rwyVwgnluoBAJZRHXkWEk\/IebvMG6fBQLAjt0KgtB2jsjZzcmsU1rzEmJV99hwCE=
    bucket: ian-arbuckle-restaurant-looker
    key: restaurant-looker-SNAPSHOT-0.0.1.jar
    bundle_type: zip
    application: RestaurantLooker
    deployment_group: spring-boot-apps
    region: eu-west-1
    on:
      repo: IanArb/restaurant-buddy-api
      branch: master
    wait-until-deployed: true
