sudo: required
language: java
jdk: oraclejdk8
env:
  global:
    - COMMIT=${TRAVIS_COMMIT::7}
    - secure: EKAe/NQusu5X7XW6WJ9uXrupz4cLmA1X1zsOlm6XgnT/grJ8MWT+bBwuB+QEVIK2DNb7vQMvloCmqs4U9EyqFe8yBxvskSsdyy9sj/xc+vv/Gb3cISGrVqnWjUZT19k2RGAaD8yps54JQ1dAD+L+E3W4Ko1wSub/uA9M+7g0moiq6VCP2dd6M0hU8UjKu98f93QO7xZZmzRd/sKh3qIPykFld24MyOv92RhV52IU0KG6FQ5r6udsrB2K3xk8+/aHkb0Si2QfnGplpzv7R+IklG8lFT2YbD5YfGTjB64xf+ivvSOACCHieJglKOdks/J6rnmuPygvThZzZPjrQRz9qzxOpYJHUjOPENWx0LagyoAzVRoMkJJa98zylKz4hQ1x05p+UaO1ePMkD934KvmvlZJHaNJ/tkRDwuKb68ZyiGyx9DOoQGiLB6Ty4UALvB0NnEsvWrUvwCLQLyC/w+RZRpC28ENuy2IBPgakBavs3DvTiPQItrwAcCbyAmy5h23/qw33xN4J3k1xjNVoOyhGgVDR1spRATYUU0oVAqn3shixg2QwnE8b2ZoYRgK4zVwqK8wx6ROTNelnQ3TvQGXo8n6+T6AOsDIhfK2thLqw6GPCeeMMadb5pO4xTHt0T9JevQjrkp22sWnBcH7d/353MBNtYqOKeBdMGgFxtiZTV+0=
    - secure: lWdEKBctAgSdA9kRXZqDhF5Ws0sx8H5GIyK+NsO+l78eB5fxFVu68gx+P40kGZpfr+WZIMbSLId/Ootcv45OdnFqC3FSBpatdMRjkA8/PFTpvvsiE+xKxlyTWbIBwMtuLoKr8NMka7Nl/7sGkPOREvj625qQLNB5g6VtwY6044miB2has9PLVTyxlRjUgYgaFenmnAYcamsHFPg0HhTpeHfvrjaz+uWbXb4kapiwfecxAotO5GBmV/uUFiH/bvo0Zu7m5nyGkhnGZzit7r6jFUsdH0YukodTEgASOYNoL4lux5H9aEn2hq49ui/Agbi/Nl9IB6L7/S9fHsqNCfPATRC0rCVt2avPKFYZaBKjlUJlYSxlPFsMlNLA1AmReoDMP3vQ7BOdnCIPmJI4hHHTmU5aSrCICm0zcsdMxMC2DzSh+E2Uh2ojQTnFrJh5HgacaDVRgZNOcQSmSB6OSif5sJWq52vVY6fb2+6jVsu9cF9kC50AjRZDI2feufGme79sgZCW8v77SjVlpfHPiTCyRBjoa9OOXzY33gopOCQiF3c+lMxBDzghQ87oxr0VCJcAujWJOKLV0e7RvNLmNeSqKqUfjCJZGbDtIksxABmNEdPhRPKyDYofSGZXNjr9sjzqc4EojGDqebeyWuqYz9hO0rIIqpthWu7OhlFSNnHHN5k=
    - secure: mxIeN/9iO6eroBJjSlhJAg4S1RCccvw2lqPvJrAoa4A2gRJSsP3avbMo8LQ8XatBw9EFagAacdsJpHotbkdvbIz2MjuolaezudCiochEad7xo41pKRwWj2XESXeXlgNRwUKvMI9Nw440D4LgrPOd7UtumpriEHyXdQ7FuGq9wXx9y5Xg9KVjQNMouW7byaPUUmlKVou/Rg5CbFHPg7Pkl/Pe9+2z2woi2sTDZ3gFYy/k00KJktfJl4MXwJOP1mm5hLod0Ke8j+h04Ez+/vmNbLNzczTdB+gdTEozd4MZRSOJDcz4ZUF7do8w5uiffqJDDy0zJRzDGTgQBI68HgU4yNZ3+CGN13sriwQ6C/x9/34glnF0WeMwa7Eb4AFoscQl/vtMJlkIHX6SYlenYWHVS/zH8USpwPoAFAtmVn3/L3+D3KewMThALI2tpZrgwR7Kh8hVg+3BVt06CeMbL7GjfT81hG+59nepPpAXPJxAyPRFVnMtCTfNn1BY5mNZOIe02PceAV2QZ5RcwWI5x3qNQDIT0s+HhCJQTm8mWcjxZAOEvL7umiYbhDvUCkCm5l9CbpVRjmVKiP5jn8fjqFS0m9HEoZ7qBwxoaKlTcp6n5t1Cb9RJSpbeA/iIeec5/TwUMR58rSNzMEO/KTfyn48L9hX61rqQ3JJRPWPydJaTHh4=
script:
  - ./gradlew clean test
  - ./gradlew jacocoFullReport
services:
  - docker
after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH;
  - export IMAGE_NAME=ianarb/restaurant-looker-api
  - docker build -t $IMAGE_NAME:$COMMIT .
  - docker tag $IMAGE_NAME:$COMMIT $IMAGE_NAME:$TAG
  - docker push $IMAGE_NAME
deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: blooming-basin-97212
