sudo: required
language : java
jdk: oraclejdk8

env:
  global:
  - secure: "MAhIUFuK1y1x+VKDPslnulDuQd5DKT6GRNAmy8HYYZQywRpZUXNBuyKrDN/BSQ7nqhET0RbAxHYge5f958+YVz7JBoRh16utjIVvuU5+Vj6AeAvRYEGjIcv2TbN9YORo0KbBi2fTlgQgjeEG4OCRvlTInBvbG5mD+0apDRe9If6c+AB/+AvDoBYy4oSTl1YKGx20QUT2wqRhMqnk61eTkpeVpYUXuGoYyugwfTVZcfcHMpxmmRasxrvcCp4Oucoq0FiNtBPaY/yMhIWehO6iy2onuQ/d5UV6b1UwsSSHt4NlZ7kk7PEQ58Fs7DAB760pYp2vpbZJi7APO6dHO/lRKpgX9/Oj7hwzE+825F85EbYXA0kBt+Oe+cAyv/3JXENTefQ7oiY+sPaTTX4GfjU9vP+qODz6/purGdMQ8s3GPb1kptCG+x2lf0gaWBZwkVeqqn2eBU3tLmzbbd2pdAWILxCuae3PxDxshn8QDJWV0ge4XK5jqXouFJplCTLsKiPKxer0jxp+aSwcKP94cOjm8Y9ni6hAAvn8FxKWD4O/Y6DDyYIBBus/vIxupysUeOv4KgopZr87yw58zLpMhUzqmR+sEjawKiT5gyc5BE57xYVnATTowv/zQX5wfOirGSRXCFHvalcTYXB6PDy21KNb7XDwO7SPPPQqgJSBMUhApqA="

  - secure: "XDJqHH9Zt2s07Mkg6NT+pQLsr2nNDqIKdbqORv8W7rfw4bZetSJSX4aay/
  ao16u+OtclmHrbkq+4OQkITSwxJR21ysRN2XNvrrlHTHPdMumd9Jr8PRrRohAwX/RBMLEdoJwjnpo2AF6qg
  4exwLbWQAlxGEjJqLgAEqz3XS3q1Usc/SiLVXIpvPKtinXhgd59Ops8oUskPtSmjDUVBfYKEnRoujYRQg5Bw
  crD8Z3wIpxZGMawLiG+2j59HcRS3Aeo/bBP8zb4huIvCJyVkSVD7eCW+oXxspUfXoEexByMvR2mxaH3ik69E69
  bnCcke70tB+lX6um7Fm7U+V3fSy4+BJbCY1qQ6eF6jEZrUM4z/QrE3FcrC4iNQ7onejS7scHo4EiFyZpTgqdZz
  4tCwOp9G8fmDQwdFOZzlGtwE1AFuElK9kPEidX3JBZvitbsA/YTWeUgU6LkPlnEbadA/JxKxmDgE8t4mtV6k5g7
  XHQaF7AstbU1tDrpN4+OpoO98BbJDXZ9SnzSmA4D00/WnlB97GBqnkA9Yip4OXjMwnAM7WUYXdUIjL3zvybPLqTw
  h+nr7I6e6hhVRpjINU2WwmYZXAha1vqWrSyS9NtVH0odrkAz1DY7AKGskRuBH/Al3uFiWcNzg3LvBsuBuxyp0UGdikZJubMsYtuAv09p+FZTWQo="
  - secure: "QyzWABgCrEPCqiK8E+/RczZfdLqysjank3eHCZXUEIKUMDNFxA63mWzNltHsIJXWhI/8ojK+TEeScFW/SS6ADzWOuxx5DAvM1+P1eJPtZHsF0T51bT7/fEju/kBcxJz3uBuYwiw90udXJBcg+qK+iohTCUhrFwbSSAmwqYlX4Jx7bZyXD4p1Lgezmw/+IVD4hBPsvDlMadH4M/4mkFFoReQ6ir5co6N6INY6QrobOciGnTqfso2pwKfkQ0NFq3080iYKaD8bjE2xdDWiU0I/Om9g5DCb9aIzMJlmfPZmy2Bu/icfDtDdLSv4bEjg0q7pRCjf4VEoZ2RpNZJn8I4qlED3lLHGteiBFYfFf6AG4lHYdVf7OjCgDF/ix0fpJ8Wlx59lW1t01D04dWthrg4yjDPW0UCkrtmXKlc2PlNYQDllg0yWxFOQP2i5yDMdS59SdOnnfmlh42EKNnSbkwpoYb+UCuBdjbRHBChnoEzsX62urNWWUbsqX7fO6vckXpGg/s3698F5yH06lYC3gsJBvYaz0zH2T2IN5joYluqXb4w4KO+UYJbuLIeNECnr+hHAJ+vllbq7BMhstdeJSPOheaYcHWsro5Ydq7Oi+pZbckIh5+iy7XCNG8XJ1kO6xQboyaHhoy3WDLf5R5QpwKjIOtO8rPgDMvS+vjeqvxqb+BQ="
  - secure: "e6ea8e58-aea2-456f-bd8b-d30c99f5f12d"
  - COMMIT=${TRAVIS_COMMIT::7}



addons:
  sonarcloud:
    organization: "ianarb-github"
    token:
      secure: $SONAR_TOKEN

script:
- ./gradlew clean test
- ./gradlew jacocoFullReport

services:
  - docker

after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH; fi`
  - export IMAGE_NAME=ianarb/restaurant-looker-api
  - docker build -t $IMAGE_NAME:$COMMIT .
  - docker tag $IMAGE_NAME:$COMMIT $IMAGE_NAME:$TAG
  - docker push $IMAGE_NAME

#deploy:
#  provider: heroku
#  api_key: $HEROKU_API_KEY
#  app: blooming-basin-97212

